spring.application.name=SWI_cafe
#------------5533 PORT ADRESA-------------
spring.datasource.url =jdbc:postgresql://localhost:5433/postgres
#-------------LOGIN----------------------
spring.datasource.username=Chooki
spring.datasource.password=KawaiiCafe
#--------------DRIVER------------------
spring.datasource.driver-class-name=org.postgresql.Driver
#--------------HIBERNATE---------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
